---
title: "About"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

## Project Objective

Using data from the World Happiness Report (WHR) and Human Freedom Index (HFI), we set out to explore how citizens' perceived happiness connects to the degree of human freedom in their corresponding countries.

We begin by presenting a broad visual of how happiness and human freedom are distributed on a global scale, noting particularly high and low ranked countries. We use linear analysis to explore the relationship of human freedom and citizen happiness, including the impact of various subtypes of human freedom. Finally, we investigate the story of "Nordic exceptionalism" by offering a closer look at Nordic countries and how human freedoms may play a role in this narrative. 

Our process of cleaning and merging these datasets is outlined in the relevant section of our project report, under the 'Report' page. 

### Screencast

<video width="320" length="240" controls>
  <source src="p8105_recording.mp4" type="video/mp4">
</video>

## About our Data {.tabset}


### The World Happiness Report 

The WHR contains survey results from participants in 156 countries on their subjective wellbeing  - in other words, how happy citizens perceive themselves to be. It explores how citizen wellbeing connects to, and can be explained by, various other influencing factors – such as GDP, government, conflicts, and social support. The 2019 report utilizes data from the Gallup World Poll (years 2005 – 2018).

The report and corresponding data can be found at: 

* [The 2019 World Happiness Report ](https://worldhappiness.report/ed/2019/)


### The Human Freedom Index (HFI)

The 2019 Human Freedom Index broadly measures the degree of human freedom in 162 countries using various indicators of social and economic freedom including, security, size of government, religion, and civil rights. It then ranks the included countries by their overall “human freedom score”.

The report and corresponding data can be found at: 

* [The Human Freedom Index - 2019](https://www.cato.org/human-freedom-index-new)

### HFI Indicators Defined

Human Freedom Score

* Measure of overall freedom – a composite score based on measures of economic and personal freedom

Economic freedom score 

* Composite score based on indicators of economic freedom such as size of government, legal system and property rights, freedom to trade internationally, and regulations

Personal freedom score 

* Composite score based on indicators of legal protection/security and specific personal freedoms (e.g., movement, religion, assembly, and identity and relationships)

Economic and personal freedom indicators used in these analyses: 

Size of government 
 
* Measure based on government consumption, transfers and subsidies, government investment, top marginal tax rate, and state ownership of assets

Assembly

* Freedom of assembly

Association

* Freedom of association

Movement 

* Based on freedom of domestic movement (freedom to travel within own country), foreign movement (freedom to leave and return to own country), and women’s freedom of movement

Rule of law 

 * Composite score based on indicators of whether countries adhere to procedural justice, civil justice, and criminal justice.

Homicide 

* Measure of intentional homicides per 100,000 population - countries with more homicides receive a lower rating

Disappearances conflicts and terrorism 

* Composite score based on indicators of disappearances, violent conflicts, organized conflicts, terrorism fatalities, and terrorism injuries

Inheritance rights

* Measure of whether women and men have equal legal rights to inheritance of land and non-land assets
