---
title: "Report"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---
# Final Report
This page contains the written report for our final project.

## Motivation
 Provide an overview of the project goals and motivation.
 In the year 2020, happiness seems to be at an all-time low. A global pandemic rages on into the new year, with cases and deaths surging to levels higher than ever seen before. Such a situation has forced many people in society to give up freedoms and individual liberties previously guaranteed in everyday life. Lockdowns, mask mandates, reduced capacity in stores and hybrid learning have all been imposed to keep people safe and healthy, yet some people see this as an infringement on their personal rights. This connection between freedom and happiness motivated our group to investigate further. 
 While we could not obtain data from 2020, we were able to obtain the most recent data possible (from 2019) surrounding global measures of happiness and freedom. Our goals were to further investigate the relationship between happiness and human freedom, with special attention towards those countries that had the actual highest and lowest scores, and countries that are colloquially thought of as the happiest and most free countries.
 
## Related Work
Anything that inspired you, such as a paper, a web site, or something we discussed in class.
Leaving this for Megan

## Initial Questions
What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?

Our primary questions were: How does happiness vary across nations?
How does freedom vary across nations? 
Does freedom have an impact on happiness/do freedom and happiness have a positive association?

These questions evolved over the course of the project after we did initial mappings and exploratory analysis. Upon noticing certain high and low rankings, we wanted to further analyze the lowest and highest ranked countries, both for freedom and happiness. In addition, we wanted to see how different subtypes of freedom were connected to happiness, not just overall freedom.

## Data

The data for this project comes from the 2019 World Happiness Report and Human Freedom Index, and can be accessed at the following links: 

* [The 2019 World Happiness Report ](https://worldhappiness.report/ed/2019/)

* [The Human Freedom Index - 2019](https://www.cato.org/human-freedom-index-new)

After importing these datasets, we performed some basic tidying (e.g., renaming variables) and selected a majority of the variables in each dataset in order to get a sense of which ones we wanted to include in our analyses. In addition, we ensured that each dataset was arranged by country alphabetically in order to successfully merge the two. We merged using 'full_join' so that all country data was represented in this final dataset. For the purpose of global maps, we wanted to include all countries available in each dataset for visualization. However, in other analyses where we planned to assess the relationship between happiness scores and human freedom scores, countries that did not have data for both indices were to be removed. Finally, we exported this final, merged dataset as a csv to use for all subsequent analysis. 

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)

# Importing and cleaning datasets

whr_df = 
  read_excel("./data/WHR20_Data.xls") %>% 
  janitor::clean_names() %>% 
  arrange(country_name) %>% 
  rename(countries = country_name) %>% 
  select(-regional_indicator, -standard_error_of_ladder_score, -upperwhisker, -lowerwhisker)

hfi_df = 
  read_excel("./data/human-freedom-index-2019.xlsx",
             skip = 4, na = "-") %>% 
  janitor::clean_names() %>% 
  filter(year == "2017") %>% 
  arrange(countries) %>% 
  select(countries, human_freedom_score, procedural_justice:personal_freedom_score, government_consumption:economic_freedom_score)

# Merging datasets
merged_df = 
  full_join(whr_df, hfi_df, by = "countries") %>% 
  select(countries, ladder_score, human_freedom_score, personal_freedom_score, economic_freedom_score, 
         religion, association, assembly, movement, inheritance_rights,
         disapperances_conflicts_and_terrorism, rule_of_law, homicide, size_of_government) %>% 
  rename("happiness_score" = "ladder_score")

#Exporting merged dataset to use for our analyses
write.csv(merged_df, "./data/merged_df.csv")

```

## Exploratory Analysis
Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.

## Additional Analysis
If you undertake formal statistical analyses, describe these in detail

### Linear analysis
After conducting exploratory analyses, we decided to conduct a linear analysis. This analysis can be found in further detail at the following link: [Linear Analysis](Linear-Analysis.html). 

The central purpose behind this analysis was to observe the relationship between happiness (assessed via ladder score in the world happiness report) and freedom (assessed by multiple measures in the human freedom index). 

To begin, we created a scatterplot, which revealed a mostly positive and linear relationship between happiness and overall freedom. In addition, we created box plots and density plots to look for outliers and normality in ladder score data and overall freedom scores. These plots revealed one outlier for freedom and mostly normal distributions (though less so for freedom). The final step before creating linear models was to assess correlation between happiness and overall freedom, in which we found a strong correlation (r = 0.69).

Prior to creating our models, we planned to include several covariates (like GDP, for example) to control for potential confounding. However, upon digging into the data, we discovered that both happiness and freedom scores actually already accounted for such covariates in their scoring system already. Therefore, we decided to make our linear models only containing variables already in the dataset. 

Our first linear model only included happiness as a function of overall freedom. Results showed a strong, positive relationship with a significant p-value, and normally distributed residuals. This result further supported the conclusion that happiness and freedom are positively associated. However, this model did not show a great degree of granularity, so we decided to create two additional, more specific models.

The second linear model included happiness as a function of economic and personal freedom. This model also revealed a positive relationship between both types of freedom and happiness, though their beta terms were smaller than the overall freedom measure's beta term. Residuals were normally distributed. Interestingly, personal freedom had a larger beta term than economic freedom, suggesting that personal freedoms (like the freedom to move, associate, practice religion, etc.) have a greater impact on happiness than economic freedoms (take that capitalism!).

The final model further broke down freedom into freedom of/from assembly, religion, association, movement, security/safety, inheritance rights, disappearances, conflict, terrorism, rule of law, and homicide. This model gave the greatest degree of granularity, but at the cost of smaller effect sizes. In this model, the only significant terms were rule of law (moderate, positive association) and homicide (small, negative association). However, the disappearances, conflicts, and terrorism term was close to being significant as well. The residuals for these models looked less normal than previous models, raising concerns about the validity of this final model.


### Top 5 Bottom 5
MEGAN

### Nordic Exceptionalism
This analysis can be found at the following link: [Nordic Exceptionalism](nordic_except.html). 

## Discussion
What were your findings? Are they what you expect? What insights into the data can you make? Limitations.

Exploratory analysis revealed a wide variation in overall happiness and freedom scores across the globe...

Linear regression analysis revealed a strong relationship between happiness and overall freedom, especially personal freedom. This makes sense, given that human beings have fought for freedom many times over the course of history. As Patrick Henry once said: "Give me liberty, or give me death". It would seem that greater freedom is associated with greater happiness, and (potentially even more so) less freedom is associated with less happiness.

This study had a handful of limitations. One notable limitation was the use of only one year's worth of data. This made the study essentially cross-sectional, and prevented any assessment of temporal changes. Future studies could build on this one by conducting similar analyses but with multiple years of data and looking at changes over time...