---
title: "Top 5 Countries"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include = F}
library(tidyverse)
library(readxl)
library(patchwork)
library(ggrepel)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r, warning = F, message = F}
merged_df = 
  read_csv("./data/merged_df.csv") %>% 
  mutate(world_happiness_score = ladder_score) %>% 
  select(-X1, -ladder_score) %>% 
  drop_na(world_happiness_score, human_freedom_score) %>% 
  select(countries, world_happiness_score, everything())
```

```{r}
bot5_whr = 
  merged_df %>% 
  arrange(world_happiness_score) %>% 
  top_n(world_happiness_score, n = -5)
```

```{r}
top5_whr = 
  merged_df %>% 
  arrange(world_happiness_score) %>% 
  top_n(world_happiness_score, n = 5) %>% 
  arrange(desc(world_happiness_score))

```

```{r}
top5_hfi = 
  merged_df %>% 
  select(countries, human_freedom_score, everything()) %>% 
  arrange(human_freedom_score) %>% 
  top_n(human_freedom_score, n = 5) %>% 
  arrange(desc(human_freedom_score))
```

```{r}
bot5_hfi = 
  merged_df %>% 
  select(countries, human_freedom_score, everything()) %>%
  arrange(human_freedom_score) %>% 
  top_n(human_freedom_score, n = -5)
```

## Tables n Plots


```{r, echo = F}
bot5_hfi %>% knitr::kable()
```

Insert comments on bot 5 hfi

```{r, echo = F}
top5_hfi %>% knitr::kable()
```

Insert comments on top 5 hfi



```{r, message = F, warning = F}
hfi_combo = full_join(bot5_hfi, top5_hfi)%>% 
  mutate(low_high = if_else(human_freedom_score > 5, "high", "low"))

hfi_plot = 
  hfi_combo %>% 
  ggplot(aes(x = human_freedom_score, y = world_happiness_score))+
  geom_point(aes(color = countries), show.legend = F)+
  geom_text_repel(aes(label = countries))+
  xlim(min = 0, max = 10)+
  ylim(min = 0, max = 10)+  
  ggtitle("Comparing Human Freedom Scores and World Happiness Scores for Top 5 and Bottom 5 Human Freedom Scores")+
  ylab("World Happiness Score")+
  xlab("Human Freedom Score")

hfi_plot
```

Insert comments about the plot hfi

```{r, echo = F}
bot5_whr %>% knitr::kable()
```

Insert comments about bot 5 whr

```{r, echo = F}
top5_whr %>% knitr::kable()
```

Insert comments about top 5 whr

```{r, message = F}
whr_combo = full_join(bot5_whr, top5_whr)%>% 
  mutate(low_high = if_else(world_happiness_score > 5, "high", "low"))

whr_plot = 
  whr_combo %>% 
  ggplot(aes(x = world_happiness_score, y = human_freedom_score))+
  geom_point(aes(color = countries), show.legend = F)+
  geom_text_repel(aes(label = countries))+
  xlim(min = 0, max = 10)+
  ylim(min = 0, max = 10)+
  ggtitle("Comparing World Happiness Scores and Human Freedom Scores for Top 5 and Bottom 5 Happiness Scores")+
  xlab("World Happiness Score")+
  ylab("Human Freedom Score")

whr_plot
```

Insert comments about whr plot
